version: '3.8'

services:
  db_example_site:
    image: mysql:latest
    # makes database data persist - this is a NAMED volume (not path based)
    # and is handled invisibly by Docker
    # we generally don't need to sync local DB contents to vc...
    # but if we did we could make this path based: ./db_data
    volumes:
      - db_data_example_site:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: sleepingkiwi
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local

  php_apache_example_site:
    depends_on:
      - db_example_site
    build:
      context: ./php
      dockerfile: dockerfile
    image: php:8.0-apache
    volumes:
      - ./php/src:/var/www/html/
      # links to our local uploads.ini to control uploads etc.
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      VIRTUAL_HOST: example-site.local

  # start phpmyadmin - not needed but useful for making Database dumps etc.
  # can comment out if not required!
  phpmyadmin_example_site:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db_example_site
    # ports:
    #   - "8000:80"
    restart: unless-stopped
    environment:
      PMA_HOST: db_example_site
      VIRTUAL_HOST: db.example-site.local
      UPLOAD_LIMIT: 500M

volumes:
  db_data_example_site: {}

# get on our local dev network!
networks:
  default:
    external:
      name: nginx-proxy
